### ISSUE TITLE
KeyError: 'LaunchConfigurationName' on  aws-vpc command

### ISSUE THREAD

**Issue by requix** [Cloud-Architects/cloudiscovery#150]
Python:        3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)]
boto3 version: 1.14.48
Platform:      macOS-10.15.6-x86_64-i386-64bit

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cloudiscovery/shared/error_handler.py", line 21, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cloudiscovery/shared/common.py", line 120, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cloudiscovery/provider/vpc/resource/compute.py", line 298, in get_resources
    data["LaunchConfigurationName"]
KeyError: 'LaunchConfigurationName'

**Comment by leandrodamascena** [comment]
Hei @requix we will fix this error in next release. I think in 2 or 3 days.

Thank you

**Comment by leandrodamascena** [comment]
Hi @requix. Sorry for the late response, I had some busy days at my regular work.

I fixed the problem. You seems like that are using ASG with Launch Templates instead Launch Configuration.

I opened a pull request #152 and we will launch a release this week.

**Comment by requix** [comment]
Hey @leandrodamascena, yes you are right, we use Launch Template.
Thanks for the fix!
