### ISSUE TITLE
Issue with Python 3.9.1

### ISSUE THREAD

**Issue by igorescobar** [Cloud-Architects/cloudiscovery#174]
Hi,

I've just installed cloudiscovery and tried to run the command bellow:

```
cloudiscovery aws-vpc --vpc-id vpc-xxxxx --profile-name x --diagram yes --verbose 
Traceback (most recent call last):
  File "/usr/local/bin/cloudiscovery", line 19, in <module>
    import cloudiscovery
  File "/usr/local/lib/python3.9/site-packages/cloudiscovery/__init__.py", line 28, in <module>
    from provider.aws.command import aws_main
  File "/usr/local/lib/python3.9/site-packages/cloudiscovery/provider/aws/command.py", line 1, in <module>
    from provider.aws.all.command import All
  File "/usr/local/lib/python3.9/site-packages/cloudiscovery/provider/aws/all/command.py", line 3, in <module>
    from provider.aws.common_aws import BaseAwsOptions, BaseAwsCommand, AwsCommandRunner
  File "/usr/local/lib/python3.9/site-packages/cloudiscovery/provider/aws/common_aws.py", line 8, in <module>
    from shared.command import CommandRunner
  File "/usr/local/lib/python3.9/site-packages/cloudiscovery/shared/command.py", line 8, in <module>
    from shared.common import (
  File "/usr/local/lib/python3.9/site-packages/cloudiscovery/shared/common.py", line 70, in <module>
    class ResourceTag(NamedTuple, Filterable):
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1876, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported
```

Any idea why that is? 🙏

**Comment by leandrodamascena** [comment]
Hi @igorescobar. Thank you for your ticket! Hmm probably problems using Python 3.9+, we haven't tested it yet.

Do you have Python 3.8* in your environment?  Could you retry the test with this version?

I'll update my env and verify it by running Python 3.9 as well.

**Comment by louiskimlevu** [comment]
same problem with python 3.9.1
TypeError: Multiple inheritance with NamedTuple is not supported

**Comment by leandrodamascena** [comment]
A new release was deployed!

Please check if it was fixed @igorescobar @louiskimlevu
